### ISSUE TITLE
Text domain should be compatible with Language Packs

### ISSUE THREAD

**Issue by christianwach** [CiviCooP/contact-form-7-civi#1]
The slug that you have on the WordPress plugin repo is `contact-form-7-civicrm-integration`. To make use of language packs, this should also be your text domain. Please see [this informative post](http://ottopress.com/2013/language-packs-101-prepwork/) for details. I'd recommend changing this as soon as possible before people implement custom translations with your current text domain.

Thanks for extending the capabilities of CiviCRM in WordPress!

**Comment by jaapjansma** [comment]
Thank @christianwach I have changed the code. However I have moved the code to the wordpress plugin directory. See https://wordpress.org/plugins/contact-form-7-civicrm-integration/installation/

I have changed the code with your suggestion!

**Comment by christianwach** [comment]
Does that mean you're using the SVN repo provided by the WordPress plugin directory for development or that you're developing here and pushing to the WP repo when you release a new version?

Most folks develop here, then push. It's _much_ harder to contribute if development isn't on Github!

**Comment by jaapjansma** [comment]
Yes I am developing on the SVN repo of wordpress. I don't know how to integrate both workflows but to publish my extension on the wordpress site I had to create a SVN repo so that is why I moved.

**Comment by christianwach** [comment]
I can recommend [this shell script](https://github.com/deanc/wordpress-plugin-git-svn) if you have an existing SVN repo. Or if you'd prefer to skip SVN entirely, there's [this version of the script](https://github.com/atwellpub/git-to-svn-deploy.sh).

Have you tried discussing code on the WordPress forums? :cry:

**Comment by jaapjansma** [comment]
Haha I haven't tried much. I am more than happy that I accomplished the task of devloping and publishing an extension for Wordpress. So at the moment I am very content.

**Comment by christianwach** [comment]
Okay, fair point. How would I get patch files to you instead of creating PRs?

**Comment by christianwach** [comment]
BTW, [it looks like](https://plugins.trac.wordpress.org/browser/contact-form-7-civicrm-integration/trunk/contact-form-7-civi.php) you still need to change `Text Domain: cf7_civi` to `Text Domain: contact-form-7-civicrm-integration` in the plugin header.

**Comment by jaapjansma** [comment]
You are right about the header. Thanks for helping out with this!

**Comment by jaapjansma** [comment]
@christianwach about the patch files. I think you can checkout the SVN repo and then commit with your wordpress.org credentials. If not I could add you as a committer to the repo... If not i am more than happy if you created a github/svn/wordpress.org integration and that we could collaborate on github.
